### ISSUE TITLE
Parse error with solrnet filter queries

### ISSUE THREAD

**Issue by Geepalem** [SolrNet/SolrNet#143]
http://localhost:8080/solr/master/select?q=_content:*&fq=({!tag=a}page_title_t:solrnet OR {!tag=b}page_title_t:solr)&facet=true&facet.field={!ex=b,a}module_fac_sm

Above query is working fine without issues.

http://localhost:8080/solr/master/select?q=_content:*&fq=({!tag=a}(page_title_t:solrnet) OR {!tag=b}(page_title_t:solr))&facet=true&facet.field={!ex=b,a}module_fac_sm

But above query (paranthesis around condition)is failing and giving below error

org.apache.solr.search.SyntaxError: Cannot parse '(page_title_t:solrnet': Encountered "<EOF>" at line 1, column 21.
Was expecting one of:
    <AND> ...
    <OR> ...
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    ")" ...
    "*" ...
    "^" ...
    <QUOTED> ...
    <TERM> ...
    <FUZZY_SLOP> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    <NUMBER> ...

I am trying to build filter queries with OR operator using Solrnet by using
SolrMultipleCriteriaQuery(sqList, SolrMultipleCriteriaQuery.Operator.OR)
and
 solrQuery = solrQuery || new SolrQueryByField(facet, value)

Solrnet is adding parenthesis around conditions which causing issues.
Could you please provide is there a way to avoid these parenthesis? Or any solution to fix this?

Appreciate your immediate help!!

Thanks,
G. Naresh Kumar

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.

**Comment by mnordeman** [comment]
Was this issue ever resolved? I am seeing the same issue when trying to accomplish facet count exclusions through solrnet. Parens are being added around my local params and solr is ignoring my tags.
SolrNet code, (new SolrQuery(new LocalParams {{ "tag","dt1" }} + $"{fq.Key}:{fq.Value}")) creates solr request, "(fq={!tag=dt1}producttype:Webinar)" which does not work because of the added parens. A valid request would be... "fq={!tag=dt1}producttype:Webinar"

I am trying to accomplish what is recommended for facet exlusions in the solr documentation.
 https://lucene.apache.org/solr/guide/7_4/faceting.html#Faceting-Thefacet.excludeTermsParameter
