### ISSUE TITLE
SolrCloud Support

### ISSUE THREAD

**Issue by AlexeyKozhemiakin** [SolrNet/SolrNet#174]
To support SolrCloud - similar to SolrCloudServer in SolrJ.
This is a top level issue which can be broken down to smaller ones.
- ability to talk to ZK to get current cluster state
- ability to send updates directly to leaders
- ability to load balance requests between replica
- ability to send query directly to correct shard when custom routing is working

**Comment by AlexeyKozhemiakin** [comment]
Here's a WIP how it may look in the end


var zkHost = "localhost:9983";
            var collectionName = "myconf";
            var num = 1000;

            var solr = new SolrCloudServer2<TestEntity>(zkHost, collectionName);

            solr.Delete(SolrQuery.All);
            solr.Commit();

            // send one by one to test sharding distribution and sending to leaders only
            foreach (var ent in GenerateTestData(num))
                solr.Add(ent);

            solr.Commit();

            var results = solr.Query(SolrQuery.All);
            Assert.AreEqual(num, results.Count, "results count");

**Comment by AlexeyKozhemiakin** [comment]
Development is taking place here https://github.com/Denis-Vlassenko/SolrNet/commits/master, after we will settle down the architecture we'll start beautifying\cleaning up the code and submitting pull requests.

**Comment by serbrech** [comment]
Great! Would it be easier to follow if you already make a pullrequest and link it to this issue?
How can I help?

**Comment by AlexeyKozhemiakin** [comment]
Here's a WIP commit for Collections API, looks very minimalistic , tested via integration tests against local solr.

https://github.com/Denis-Vlassenko/SolrNet/commit/571e74258033d64cbe9dfb754faa6bd5221a1d2b

**Comment by AlexeyKozhemiakin** [comment]
@mausch could you please have a look at our WIP branch and share your thoughts? 

https://github.com/Denis-Vlassenko/SolrNet/commits/master,

We are on final phase, passed several iterations of archtiecture rewriting, adding more unit\integration tests, polishing. Documentation will follow also soon after we will settle with approach.

**Comment by xaviermorera** [comment]
I have been asked to help on a Solr project where I believe SolrNet is ideal. I proposed SolrNet as the way to go to use Solr instead of manually coding Solr commands and sending to /select and /update. You know what I mean :)

However, I was told that "No SolrNet because it does not support Solrcloud".  So then I see this issue and the reference to https://github.com/Denis-Vlassenko/SolrNet/commits/master.'

So I get asked if the changes in this fork will be added into this repository.

So my question is, does anyone know if it is in the plan to do the pull requests and merge back here? Apologies for being direct, just that I believe SolrNet will make a difference in this project.

**Comment by mausch** [comment]
@xaviermorera I encourage you to try @AlexeyKozhemiakin 's bits and report back here with any feedback. In my opinion OSS development should be as distributed as possible, not everything must go through the maintainer. Also, I think it's best that features be developed by people actually using them, and I don't have a use for this now. I could only offer general advice.
Moving to a different continent while juggling two jobs has cut down my OSS time significantly, so I'll be slower to reply.

**Comment by xaviermorera** [comment]
Thanks @mausch I will talk to @AlexeyKozhemiakin on this matter. I indeed have a need and good luck to wherever you are going!  And you are completely right on OSS, just that I wanted to check first here.

**Comment by AlexeyKozhemiakin** [comment]
Hello @xaviermorera and @mausch . We're running new solrnet with cloud support on several projects for customer and internal ones. We'll create push-request in nearest future, after adoption to solr5 (way of managing cluster state in zookeeper changed dramatically).

@mauch - i've sent you several email, unfortunaly didnt get any reply. In order to commit the changes and bring more users to solrnet we will need your support or at least some effort to review architecture and changes. Do you think you could help us and community? As an alternative I can serve as commiter\reviewer for solrnet - since I have resources to support it now.

**Comment by DarrenJohn** [comment]
Pardon the interruption...
What is the status of this SolrCloud Support effort?  

We have been running on SolrNet for a couple of years now, and are getting to the point where we need to distribute the load.  I haven't seen much development in 8 months, and was hoping to incorporate this effort.

Thanks in advance,

**Comment by AlexeyKozhemiakin** [comment]
Hi @DarrenJohn, most effort was incorporated back to solrnet master branch. Let me come back to you on Monday with detailed instructions how to use it.

**Comment by dkrupnou** [comment]
Hi @DarrenJohn,
I'm @AlexeyKozhemiakin's subordinate and I'll help you with SolrCloud.

First of all, if you need to add SolrCloud support to your application, you have to fetch our pull request into your fork of @mausch SolrNet repository. Here the link to [cloud's pull request](https://github.com/mausch/SolrNet/pull/187). Branch name is "dkupnou/cloud" and heading of this pull request is "Solr cloud support draft version".

After that you will be able to use SolrNet in cloud mode. The usage of SolrNetCloud is similar to basic SolrNet. You can find the documentation of usage in "Documentation/Basic-usage-cloud.md" and "Documentation/Collections-api.md" or read it on my fork. 
[Basic cloud usage] (https://github.com/dkrupnou/SolrNet/blob/cloud/Documentation/Basic-usage-cloud.md) 
[Collections api] (https://github.com/dkrupnou/SolrNet/blob/cloud/Documentation/Collections-api.md)

Please, feel free to ask if there are any questions.

Thank you

**Comment by maggon** [comment]
Hi @AlexeyKozhemiakin @mausch - any idea on when this can be merged into the master?

**Comment by perzzon** [comment]
Hi! Also curious about this...

**Comment by gquaire** [comment]
Hi. 
Do you have more information abot the merge into the master branch?
 I am very interesting about this feature too.

Thank you.

**Comment by JeffPalmier** [comment]
Hi,
I have seen that it just need to be merged into the master branch. Sounds good.

Do you jnow when it could be merged ? I am really interested about the SolrCloud Support.

Thanks

**Comment by mausch** [comment]
@gquaire @JeffPalmier @perzzon @maggon have you tried this code? I haven't needed SolrCloud myself yet so I was looking for feedback from other users. Cheers.

**Comment by JeffPalmier** [comment]
Thank you @mausch. I will try the code and give you some feedback about it.

**Comment by gquaire** [comment]
Hi @mausch, We have not tried the code yet . But, we will do it. We will keep you updated.

Thanks for your reply.

**Comment by shivendra31** [comment]
Hi,
I am trying to integrate SolrCloud to my asp.net application. How to integrate and we need to integrate it. Can anyone help me please.
I am new with solr technology.

Thanks

**Comment by richetdan** [comment]
Which solution are suitable in order to use solrcloud with solrnet?

- Making direct solr REST Http request using Zookepeer.Net to ask for availables nodes and manually make something like a round robin?
- Using some stuff which support zookeper.net as external proxy/load balancer?
- evaluate the use of Elasticsearch instead of Solrcloud?
- Try to use the fork suggested ? (I tried with little luck)

I will appreciate any suggestion, I've invested time studing, configuring and testing solrcloud discovering that Apache does not provide any client for .net environements.
dr

**Comment by dkrupnou** [comment]
@shivendra31 @richetdan 
Hi guys, 
We're using this SolrCloud implementation in production and it seems okay.

Did you have a chance to read and follow [basic cloud usage] (https://github.com/dkrupnou/SolrNet/blob/cloud/Documentation/Basic-usage-cloud.md)?

In case of any question please feel free to ask me.
Thank you.

**Comment by richetdan** [comment]
Thank you @dkrupnou,
do you mean this implementation? https://github.com/vladen/SolrNet

I've tried, downloaded the inline sourcecode, compiled, referenced into my test project those libraries:
- SolrNet
- SolrNet.Cloud
- SolrNet.Unity
- SolrNet.Cloud.Unity

SolrCollectionsAdmin works but I can't get an instance of ISolrOperations in order to do queries because the line
```
Startup.Init<Product>(new SolrCloudStateProvider(zookeeperConnectionString), collectionName);

```
throws error.

I am using solrcloud 5.5.1 with one external zookeper.

**Comment by dkrupnou** [comment]
@richetdan 
here is the latest version https://github.com/mausch/SolrNet/pull/187.

Also, ensure that "Startup" is used from SolrNet.Cloud instead of SolrNet project, for now both of these projects have the same name for startup class and it could be confusing.

**Comment by richetdan** [comment]
Thank you.
I will try version 187 ASAP, however I am sure to call "Startup" method from SolrNet.Cloud namespace.

**Comment by dkrupnou** [comment]
It would be great if you could post the exception with stack trace to investigate

**Comment by richetdan** [comment]
Ok guys, thank you so much for helping!
with the version suggested by @dkrupnou it works.... but it works on first attempt, the second one cause a crash on the primary node of the cluster . Maybe the reason is I have done "Startup" 2 times, however seems quiet unstable to adopt this solution on a critical production environement.

**Comment by dkrupnou** [comment]
@richetdan 
Please look at @mauch initialization document - https://github.com/mausch/SolrNet/blob/master/Documentation/Initialization.md, Startup should be called once at application startup, next Startup calls will be failed. The same situation is here

**Comment by richetdan** [comment]
I've placed Startup on global.asax, but this not changed.
However the greatest problem is not the error on the client side but is the crash of the solr server!

**Comment by dkrupnou** [comment]
Could you share solr server logs please?

**Comment by richetdan** [comment]
There are no entry related the last 2 hours in the solr.log.
However: 

http://pastebin.com/iGpm03GN

**Comment by dkrupnou** [comment]
Actually, I can't see any exceptions in your log file which led to crash your solr server as you mentioned before. What kind of crash did you mean?

**Comment by richetdan** [comment]
I mean I've got a SolrConnectionException on the client side when executing the Query.ALL and the leader server node result "gone"

**Comment by xaviermorera** [comment]
I am working on a project with SolrNet + SolrCloud. We are only allowed to use mausch's and no forks so here is what we did:
- At index time, we make a call to clusterstate.json and using Json.Net I parse and extract the leader so I submit all updates to that node. 
- And then we have a load balancer in front of the cluster, so calls are distributed evenly.

It works without too much hassle.

**Comment by richetdan** [comment]
thank you very much xaviermorera, now I am gonna test elasticsearch which has native .net client and then I will choose between your solution and elastic.

Which kind of loadbalancer are you using?

Thank you very much for all contributions from all users

**Comment by richetdan** [comment]
Ok, guys, the fork it works, I think it was just a memory problem (running default settings on server).
It is still not clear beacause there wasn't any OutOfMemoryException.

However, brutally killing one of the solr node's process cause problem on solrnet.cloud client routing (some requests continue to be forwarded on dead node).

**Comment by shivendra31** [comment]
Thank you  @dkrupnou 
I have downloaded source code from this location: https://github.com/vladen/SolrNet but it have lot of directories so, please guide me which directory useful for me as I am trying to implement in asp.net application.
I have installed Solr-5.3.1 on two machine and Zookeeper-3.4.8 on single machine, created a collection and two shards.
Please let me know what I have needed and what step need to follow to configure solrcloud in asp.net application.

Thank you very much

**Comment by richetdan** [comment]
Hello @Shivendra, I can only suggest to adopt the @xaviermorera 's solution with external loadbalancer or adopting java on the client side or change the server side system. Solrnet does not support solrcloud, the fork that has been mentioned is very unstable and buggy. Considering that the last pullrequest to the original project was made more than a year ago, I would not do much reliance on the fact that in the nearest future solrcloud will be supported by solrnet.

**Comment by xaviermorera** [comment]
@richetdan it is hardware load balancer.

**Comment by sirea07** [comment]
@mausch Could you tell us please what is necessary for you to merge this fork? I would like to use SolrNet in a large project with installations around the world and therefore SolrCloud is kind of crucial to us. Thanks.

**Comment by shivendra31** [comment]
Hello @richetdan and @xaviermorera , Is it possible to implement SolrCloud for .net client without hardware load balancer.
If it is possible, please suggest
Thanks!

**Comment by dkrupnou** [comment]
@shivendra31, this fork already has this feature, to loadbalance using code instead of specific hardware

**Comment by shivendra31** [comment]
@dkrupnou thanks for such a quick reply. Can you please provide me link of right fork.

**Comment by dkrupnou** [comment]
@shivendra31 here is the [link](https://github.com/mausch/SolrNet/pull/187) to active SolrCloud Pull Request . And [here](https://github.com/dkrupnou/SolrNet) you can find right fork, branch name is "cloud".

By the way, at this moment this implementation has simple replicas load balancer based on random node index generation. If it's not enough, we can extend this solution with RoundRobin balancer if needed.

Thank you.

**Comment by shivendra31** [comment]
@dkrupnou I have downloaded fork and build it and added dlls into my application but not get instance of zookeeper.
Startup.Init<Product>(new SolrCloudStateProvider("127.0.0.1:2181"), collectionNames, true);

throws error.
The type initializer for 'ZooKeeperNet.ZooKeeper' threw an exception.

**Comment by dkrupnou** [comment]
@shivendra31 please ensure that external zookeeper is started and running on port 2181. If you are using internal zookeeper which is embedded into solr, please change the port number (default port is 9983).

**Comment by shivendra31** [comment]
Hello @dkrupnou,

 What is "/clusterstate.json" in SolrCloudStateProvider class. Is it need to change following variables?. Because ran into issue on line 
state = GetInternalCollectionsState().Merge(GetExternalCollectionsState());

throws error.
The request /clusterstate.json timed out while waiting for a resposne from the server.

   public const string ClusterState = "/clusterstate.json";
    public const string CollectionState = "state.json";
    public const string CollectionsZkNode = "/collections";

    private void Update(bool cleanZookeeperConnection = false)
    {
      if (zooKeeper == null || cleanZookeeperConnection)
      {
        if (zooKeeper != null)
        {
          zooKeeper.Dispose();
        }
        zooKeeper = new ZooKeeper(zooKeeperConnection, TimeSpan.FromSeconds(10), this);
      }
      state = GetInternalCollectionsState().Merge(GetExternalCollectionsState());
    }

Thanks!

**Comment by dkrupnou** [comment]
@shivendra31 

The cluster state variable is used for supporting old version of solr (< 5.0), when all collections information was stored in a single clusterstate file. Since 5.0 version of solr, each collection has it's own state, which is called state.json. This code tries to get all possible states and merge them.

According to the exception, I can see only two possible reasons of it, first - your connection string to zookeeper is wrong, second - maybe your cluster state file is big enough so the time to receive it from zookeeper is more than 10 seconds timespan.

Could you please verify that zookeeper is reacheable by your connection string (try to connect by zkCli command line), if so, try to increase the timespan and rebuild the solution. This timespan was choosen experementally so it's ok if we should increase it by default or make it configurable.

Hope it'll help.
Thank you.

**Comment by shivendra31** [comment]
Thanks @dkrupnou  

SolrCollectionsAdmin works and Startup is used from SolrNet.Cloud also working showing zookeeper connected: Is following line is correct?
 Startup.Init<Product>(new SolrCloudStateProvider(zookeeperConnectionString), collectionName);

But, I can't get an instance of ISolrOperations in order to do queries because the line. using ISolrOperations from SolrNet.Cloud.
var solrCloudMode = ServiceLocator.Current.GetInstance<ISolrOperations<SolrProductCorecl>>();

When using .ISolrOperations from SolrNet
var solrCloudMode = ServiceLocator.Current.GetInstance<SolrNet.ISolrOperations<SolrProductCorecl>>();

 threw error:
 The given key was not present in the dictionary.

Also not getting instance of SolrQueryByField for SolrNet.Cloud
var results = solrCloudMode.Query(new SolrQueryByField("in_website_id", "1"));

Please suggest
Thank you.

**Comment by shivendra31** [comment]
Hello @dkrupnou,

Configured Single node Zookeeper- 127.0.0.0:2181
Configured Solr :
![solr](https://cloud.githubusercontent.com/assets/19397215/15820514/922e2ae0-2c07-11e6-9e38-4475b720b422.PNG)

When I am trying to call ISolrOperations from SolrNet
var solrCloudMode = ServiceLocator.Current.GetInstance<SolrNet.ISolrOperations<SolrProductCorecl>>();
var results = solrCloudMode.Query(new SolrNet.SolrQueryByField("id", "SP2514N"));

Threw Error on following function:

File --solrnet.unity\container.cs
 protected override object DoGetInstance(Type serviceType, string key)
 {
       if (key == null)

           return componentsByType[serviceType][0](this);
            return componentsByName[key](this);------------componentsByName.count is 0
 }

Error:
The given key was not present in the dictionary.

**Comment by shivendra31** [comment]
Hi, @richetdan,

I am also facing same problem as you mentioned previous for ISolrOperations instance please suggest what i have need to do.
Please see previous two comments.

Thank you very much.

**Comment by richetdan** [comment]
Hello Shivendra, this is the code I used to test that fork:

`string zookeeperConnectionString = "10.80.1.77:2181";
var collectionName = "your_collection_name";
SolrNet.Cloud.Startup.Init<TKDocumento>(new SolrCloudStateProvider(zookeeperConnectionString), collectionName);

var solrCloudMode = ServiceLocator.Current.GetInstance<ISolrOperations<TKDocumento>>();
var results = solrCloudMode.Query(...);
`

In addition, to avoid the solr server to crash I had to raise the heap memory on the server; which it is totally unreasonable because with solrj I have not had this need for the same load.

In any case, as I have said repeatedly, I strongly advise against using this fork in the production environment, because it simply does not handle correctly falut tolerance and because it is very unstable and can not have any kind of support.
you can just hope that it will be merged into a stable release on the master project.

Personally I switched to Elasticsearch since it has a .net client natively supported and perfectly working on cluster mode. Other chance is to use external loadbalancer.
good luck.

**Comment by shivendra31** [comment]
Thanks @richetdan,

It was issue with document now it working. 
Please let me know how to get current node details from which zookeeper get data.

Because I have to call HttpWebRequest with "Solr node + query".
HttpWebRequest oWebRequest = (HttpWebRequest)WebRequest.Create(Solr node + query);

Thanks!

**Comment by blmille1** [comment]
I could really use cloud support.  Any idea when this will be available?

Thanks!

**Comment by RageRabbit** [comment]
Hi, everyone!
I've recently joint @AlexeyKozhemiakin's team and made commits into this fork (completed collection api and fixed cluster state update issue - not capturing all clusterstate events).

@gquaire @JeffPalmier @perzzon @maggon @serbrech @DarrenJohn @blmille1 @shivendra31  , have you tried latest/any version of this fork and, if you please, can you provide some feedback?
maybe, after that, @mausch will consider to merge it to master.

Glad to help and fix code. if needed

**Comment by AddictedCS** [comment]
@RageRabbit @AlexeyKozhemiakin @mausch Is this thread still alive?

Would really appreciate your thoughts on when will SolrCloud be part of the NuGet package (or at least merged into this repo).

Thanks!

**Comment by xavier-morera** [comment]
Hi @AlexeyKozhemiakin, would you like to talk about adding SolrCloud as part of SolrNet? SolrNet has been moved to an organization and so we can collaborate to bring new life to this great project

**Comment by AlexeyKozhemiakin** [comment]
hi, sure!

We were looking to finally push that and update nuget packages long time
ago. How can we help now?

**Comment by xavier-morera** [comment]
Hi @AlexeyKozhemiakin how much testing have you done with SolrCloud?  Is working fine, in production, rock solid? Or does it still require a bit of extra work?  

Also, I would like to test myself as well. I can see pull request **Solr cloud support draft version #187**, which I want to confirm it is the latest version that you were working on. I can see the comment of it being the latest version of vladen's branch too, but want to check what else has changed. 

Including @dkrupnou  and @janhoy

**Comment by janhoy** [comment]
I'm happy that the project is set free from its former state of inactivity. It's simply depressing to see 26 open PRs.. Hope you manage to attract a solid number of committers so this does not die again should @xavier-morera switch jobs or lose interest.

Also wanted to let you know about the recent effort in https://issues.apache.org/jira/browse/SOLR-10446 which will ship with next version. It means you can get cluster state over HTTP from one of the Solr nodes and don't need to talk to ZK at all.

**Comment by xavier-morera** [comment]
@janhoy I will most definitively not lose interest nor participating in this project is because of my job. I am tight on time though and there are a few things I need to get up to speed here, so I will try my best with the available time I have. 

Regarding the JIRA, it targets Solr 6.6 but we still need to support 4.x (at least), 5.x and 6.x so that is what I am trying to determine what will be the best way, including multiple .NET platforms. Once I get confirmation of the solrcloud fork with the latest bits I will merge into solrcloud branch for testing.

**Comment by xavier-morera** [comment]
Closing this one to continue in issue [187](https://github.com/SolrNet/SolrNet/pull/187)

Just a note, I have pulled dkrupnou/SolrNet:cloud into https://github.com/SolrNet/SolrNet/tree/solrcloud which is ready to merge after some testing. This will add SolrCloud support.
