### ISSUE TITLE
Upgrade to modern unit test framework

### ISSUE THREAD

**Issue by AlexeyKozhemiakin** [SolrNet/SolrNet#175]
(discussion moved from twitter https://twitter.com/AlexKozhemiakin/status/550071605888835584) 

MbUnit\Gallio are quite outdated and not supported by modern IDEs, which makes  the process of preparing new contributions rather difficult(annoying). The ultimate goal of this issues - is to facilitate this process in terms of easy test running.

Let's agree on strategy where to migrate. I spent (just) 30 minutes to migrate 600+ tests to NUnit (90% was AutoReplace) which had a huge immediate result - I can run and debug tests in VS2012\2013.

Such fast migration suggests that tests use-cases are quite straightforward and can be migrated to any test framework relatively easy. 

I dont have a bias towards NUnit, anything that is up-todate and requires minimal efforts to migrate is fine. XUnit? ^)

@mausch any thoughts?

**Comment by AlexeyKozhemiakin** [comment]
+1 to sergey, it's crucial to success of solrnet (and anyother open-source) to be newbie friendly. Currently nuget package is not compatible with 4.x version, and it's really annoying. We have many projects at our company and we result in sharing our own copy of solrnet, but it is not how it should be.

Solrnet right now looks a bit abandoned, we are full of enthusiasm to fix most critical issues and spend decent amount of time to beatify it.

Which means we have to be truly pragmatic - test framework should just minimize pain in our development efforts. I dont know how can I do it in MbUnit except for commandline etc.

Probably it makes sense to separate the goal of creation a superb test library (for sake of engineering) and maintaining tests in solrnet (for sake of pragmatic approach and making solrnet more usable and popular).

I hope you will listen to voices of your users and contributors.

**Comment by AlexeyKozhemiakin** [comment]
>> About that I wonder how you translated the tests that use [StaticTestFactory].
Majority of such tests resulted in TestCaseSource with reference to datasource array.
     
   [Test, TestCaseSource("parsedDates")]
        public static void ParseYearsTest(KeyValuePair<string, DateTime> pd)
        {
            Assert.AreEqual(pd.Value, DateTimeFieldParser.ParseDate(pd.Key));
            Assert.AreEqual(pd.Value.Kind, pd.Value.Kind);
        }

A few tests unfortunately were flattened to one big test with many asserts, but I'm sure it can be improved by separating to separate methods + test case sources.

**Comment by mausch** [comment]
Just a few hours ago I answered a question on Stackoverflow about [how broken Xunit and the R# test runner is](http://stackoverflow.com/questions/27726058/passing-discriminated-unions-to-inlinedata-attributes). 
Just a couple of weeks ago I upgraded to ReSharper 9 at work and couldn't run MSpec tests any more.
I will not make this mistake again as long as I have a say about the matter. This is a waste of everyone's time and not the way to go.

About https://www.nuget.org/packages/Solr.NET/0.4.0.2004-alpha I'd say it's more likely that this person wanted a more recent build than the one currently published on nuget.org but we're really both guessing, let's not do that.

Making things "easy" for new contributions is terribly subjective. Someone could say that me trying to enforce immutability now is making things harder. Or that using FAKE for the build makes it harder for people to add things there because they don't know F#. Dumbing things down to the lowest common denominator doesn't work long-term. Instead, we have to keep raising the bar. And NUnit, being utterly broken (the code you show is a tiny sample of this), is a *downgrade* from MbUnit.

If something is unclear about running tests or anything else, then we should simply document it. And in fact, if the project looks abandoned it's because it needs documentation, but nobody ever wants to contribute that, and this being just a few markdown files on github it's as easy as it can be. I'm even considering now to enforce that anyone contributing some code should not only contribute also the corresponding tests but the documentation as well. But again this might make things "harder" for new contributors (see my point now?).

Committing the library binary or not is also [up for discussion](https://twitter.com/jeffreypalermo/status/534907671049404418), not necessarily 100% a bad thing. But I agree that updating the nuget package is important, which leads again to the issue of documentation.

**Comment by stephenpope** [comment]
I have to be honest here and register my preference here that I don't like running MbUnit .. Gallio and all its crap are a pain in the ass (especially from a clean install) and have actively put me off fixing some things in the past.

Its not about MBUnits functionality or if its is doing the job correctly over (x)Unit but I too like to have my tests running in the IDE with NCrunch/Resharper etc while I'm coding and I've gone down the same path of converting the unit tests to XUnit and then back to MBUnit in the past just to fit into my usual development workflow and when i have time to mess around getting Gallio to run my tests correctly (yes, ridiculous and pointlessly time-consuming as it sounds!)

I think it is important that new contributors can dip in and contribute quickly and things naturally end up in the right place (easier said than done i know!)

**Comment by 0xcfff** [comment]
I'm agree that making things easy for newcomers is very important. IDE support for unit test frameworks is one of things that made unit testing popular and it is strange to discard this feature just because of some imperfectness in the test library. I would say that all this thread looks as a holywar around the theoretical aspects rather than around some real problems. 
I've looked into test examples in different frameworks mentioned above and I don't really see much difference between them. Yes, they have slightly different syntax, they have difference in features and not all of them support first class tests. But, any of these tools provide enough functionality to solve any sort of problem related to unit testing. If some library does not have some particular functionality, it can usually be replaced with something and all the difference will be only in syntax.
Regarding "raising the bar", it is also terribly subjective. For someone it is "raising the bar", for others it is waste of time on learning of an unpopular and outdated library. Also, it is waste of time to work with unit tests from outside of IDE. Yes, NUnit runners may break one day but they will be fixed very quickly because NUnit has giant number of projects using it and this, in fact, will be the driver to fix this problems ASAP and before that moment, old runners can be used.

**Comment by ny6asik** [comment]
I agree with previous speakers, 
It's very important to run the project easily without any outside manipulation (such as annoying work with MbUnit). 
So, it will be cool to change current testing framework to another one which will grant all testing features inside IDE without magic

**Comment by serbrech** [comment]
I'll have to agree as well with the mass here.
I have done minimal contributions to SolrNet in the past, and I remember that the biggest pain in the process was trying to get the Gallio stuff working. The tooling is absolutely terrible, nobody is familiar with it.

You say you got bitten by MSpec recently, but MSpec has its console runner, so that should not really be a problem. Probably the frustration you felt then, is about the same as every contributor to SolrNet felt when we tried to help.

I totally agree on the principle, when you refuse to go for the lowest common denominator, but there has to be some middle ground somewhere.

What if we had a script that would setup everything correctly? Download, install, and verify?
Would that help remove the friction...

**Comment by Denis-Vlassenko** [comment]
If I lived in a perfect world, I'd write ideal code from scratch. 
My vote for IDE support to stick with defaults. 
However, I love functional approach with intuitive DSL and without any magic behind. At the same time plenty of devs are building solutions using ill-designed and outdated libraries not even imagining the better option.

**Comment by xavier-morera** [comment]
Moved to XUnit
