### ISSUE TITLE
Documenting SolrNet

### ISSUE THREAD

**Issue by xavier-morera** [SolrNet/SolrNet#180]
I would like to help build the Documentation for SolrNet for developers. Is this other people are interested in helping as well? Let me explain the background.

I am a .Net developer who created a training on Solr for Pluralsight called [Getting Started with Enterprise Search using Apache Solr](http://www.pluralsight.com/courses/enterprise-search-using-apache-solr) where I show how to get started with Solr and it ends with a demo where in 17 minutes I show how to build build a small UI for your Solr using SolrNet. I also recently finished writing a book on Solr that will be published recently where I also point developers to SolrNet.

I am thinking of creating a course on documentation using Atlassian Confluence. I think that as part of my course, I can help put together the documentation for SolrNet but will need some additional help from the community. 

Is this something people are interested in helping with?

**Comment by AlexeyKozhemiakin** [comment]
hi @xaviermorera , this is hilarious, thanks for volonteering!

Documentation is what solrnet needs a lot at this point, it's currently blocking release of nuget package. Here's what @mausch commented about it https://twitter.com/mausch/status/549914952505765888 

So if you could start this effort it would be great.

Also I anticipate some changes to be contributed by us to solrnet in nearest future, including solrcloud and change of how it's working with dependency injection. all this stuff will require documenting as well.

So please keep in touch and let's make solrnet better together!

**Comment by xaviermorera** [comment]
The question I have is does it need to be documented in Github or can it be done in Confluence. Any thoughts?

**Comment by AlexeyKozhemiakin** [comment]
I'd definitely prefer to keep it here in GitHub wiki pages (github) currently they are here https://github.com/mausch/SolrNet/tree/master/Documentation, but from end-user perspective i'd consider moving them to wiki. @mausch had it's own thoughts about it here https://github.com/mausch/SolrNet/issues/175

>>If something is unclear about running tests or anything else, then we should simply document it. And in fact, if the project looks abandoned it's because it needs documentation, but nobody ever wants to contribute that, and this being just a few markdown files on github it's as easy as it can be. I'm even considering now to enforce that anyone contributing some code should not only contribute also the corresponding tests but the documentation as well. But again this might make things "harder" for new contributors (see my point now?).

>>Committing the library binary or not is also up for discussion, not necessarily 100% a bad thing. But I agree that updating the nuget package is important, which leads again to the issue of documentation.

**Comment by xaviermorera** [comment]
Let's see what @mausch has to say. I would definitively have more time available to work in Confluence.

**Comment by AlexeyKozhemiakin** [comment]
And by Confluence you mean external resource, like what for example? 

Why do you think it's better than having it all in once place hosted on github ?

**Comment by xaviermorera** [comment]
I mean in Confluence as in what Apache uses for all its projects, here is whre the Solr Reference Guide lives: https://cwiki.apache.org/confluence/display/solr/Apache+Solr+Reference+Guide

**Comment by mausch** [comment]
Thanks for the comments everyone. Here are the benefits of the current documentation system and why I chose it when I migrated from code.google.com to github (I also partially explained this in https://github.com/mausch/SolrNet/issues/178 ):

 * Versionable, right along with the code. Github wiki is versionable but not along with the code, it's a separate repository. Github pages is also versionable but not along with the code, it's a separate branch. Similar with any other external wiki.
 * Branch-specific docs: kind of a corollary of the above, but it's worth mentioning that you can have separate documentation for each branch. This means that you can work on a feature branch and write the docs and then send a pull request for everything, without affecting the documentation on master or other branches. A few days ago I started working on the [missing documentation for 0.4.0 on a separate branch](https://github.com/mausch/SolrNet/tree/0.4.0b3). Can't do this on any of the other documentation systems AFAICT.
 * Github workflow: the fork / pull request workflow is simply brilliant (by now I don't think I have to spell out here why). Very few external wikis are git-based.
 * File-based: When I started working on the docs for 0.4.0 a few days ago I simply copied the 'documentation' directory and edited the files offline before pushing them. Usually can't do this with external wikis or it's awkward/inconvenient.
 * Offline access: as a corollary of the above, anyone that clones the repo has the docs for offline reference. Markdown is easily readable as plain text, you can grep the files, etc.
 * Single account: contributors don't need to create any additional accounts as with an external wiki.
 * Potentially compilable: I'd love to have any code snippets in the documentation checked by the compiler. AFAIK this is only available for F# right now (with FSharp.Formatting) but since many ideas from F# trickle down to C# I can see this happening in a not-so-distant future. This requires that the docs have many of the properties I mentioned above.

 The only benefits I see in using gh-pages or an external wiki are: prettier output and somewhat better navigation. Hardly worth giving up all the properties I mentioned here IMHO...

**Comment by xaviermorera** [comment]
@mausch has a very valid point.

**Comment by AlexeyKozhemiakin** [comment]
@mauch @xaviermorera thanks guys.

in any case it's content that matters, I wouldn't be too far from truth if I would say that having all documentation ready it's a matter of several hours to migrate them to any doc-system.

So if @xaviermorera you still feel enthusiastic about brining more documentation to solrnet - let's do that! I've started a page about solr cloud that will be published shortly.

https://github.com/mausch/SolrNet/tree/master/Documentation

**Comment by xaviermorera** [comment]
Enthusiastic, yes. Need to finish the current training first. Will come back to this after I am done.

**Comment by xaviermorera** [comment]
Hi. I have finished what I was working on and I can help starting on documenting a bit. In your opinion, what would be a nice place to start? Where do you think the documentation needs a bit of improvement? Or should I just start reviewing and helping little by little from the start?

**Comment by mausch** [comment]
Thanks @xaviermorera . Just off the top of my head:

Pivot faceting for example is currently undocumented: https://github.com/mausch/SolrNet/blob/master/Documentation/Facets.md#pivot-faceting

Some faceting options, like limit, are not mentioned there.

People keep getting confused about `ExtraParams`: it's usually used as a dictionary, but doesn't have to be (e.g. http://stackoverflow.com/questions/29147725/how-do-i-pass-multiple-bq-arguments-to-localparams-in-solrnet ). Maybe worth mentioning somewhere, at least in the FAQ.

The extract feature (i.e.. https://github.com/mausch/SolrNet/blob/master/SolrNet/ExtractParameters.cs ) is currently undocumented (other than xmldocs).

I started documenting https://github.com/mausch/SolrNet/commits/0.4.0b3 (i.e. not master) by copying the docs from master, but this needs to be revised for the actual features of 0.4.0.

https://github.com/mausch/SolrNet/blob/master/Documentation/Multi-core-instance.md is probably out of date.

https://github.com/mausch/SolrNet/blob/master/Documentation/Highlighting.md is quite sparse.

Grouping is undocumented: https://github.com/mausch/SolrNet/blob/master/Documentation/Field-collapsing.md#for-solr-33

We should probably start linking the reference guide https://cwiki.apache.org/confluence/display/solr/Apache+Solr+Reference+Guide instead of the wiki.

**Comment by xaviermorera** [comment]
Thanks Mauricio! I started last week on project that uses SolrNet so I will definitively use some of those features which I will document as I go along. I will get started. Thanks!

**Comment by xaviermorera** [comment]
Hi. @mausch. Quick question on pivot facets. I made this change in the documentation, do you believe it is complete for merging or should I elaborate more? 

https://github.com/mausch/SolrNet/pull/196/commits

Please let me know and I will work on getting it done right.

**Comment by waleedraza786** [comment]
An unhandled exception of type 'SolrNet.Exceptions.SolrConnectionException' occurred in SolrNet.dll

Additional information: <?xml version="1.0" encoding="UTF-8"?>

<response>

<lst name="responseHeader"><int name="status">400</int><int name="QTime">428</int></lst><lst name="error"><lst name="metadata"><str name="error-class">org.apache.solr.common.SolrException</str><str name="root-error-class">org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException</str></lst><str name="msg">Exception writing document id df947450-8e8d-4961-ab09-d41778fcf8aa to the index; possible analysis error: Document contains at least one immense term in field="doctext" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[50, 52, 48, 48, 32, 65, 46, 68, 46, 32, 67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 49, 57, 56, 55, 32, 79, 114, 105, 103, 105]...', original message: bytes can be at most 32766 in length; got 41389. Perhaps the document has an indexed string field (solr.StrField) which is too large</str><int name="code">400</int></lst>

</response>


I got this exception during indexing in asp.net 
it was working perfactly when i was using solr 1.4 version with tomcat. Now i cannot directlly asp.net to solr but i m facing this issue
