### ISSUE TITLE
SolrFacetDateQuery needs to be updated to solr 6 specifications using facet.range instead of facet.date

### ISSUE THREAD

**Issue by jamesewelch** [SolrNet/SolrNet#312]
https://lucene.apache.org/solr/guide/6_6/major-changes-from-solr-5-to-solr-6.html

facet.date.* Parameters Removed
The facet.date parameter (and associated facet.date.* parameters) that were deprecated in Solr 3.x have been removed completely. If you have not yet switched to using the equivalent facet.range functionality you must do so now before upgrading.

SolrFacetDateQuery creates "facet.date" URL parameters. This should be updated to "facet.range" to work with Solr6 implementations.

**Comment by xavier-morera** [comment]
Thank you @jamesewelch, it is in the TO DO list. We need to make it in such a way that we support older versions of Solr too. 

Would you be interested in helping by forking and helping implement this feature? We would love to get another contributor on this project.

**Comment by gjunge** [comment]
@xavier-morera , @jamesewelch , has already been taken care of in PR #309  , which sits now in the development branch. 

@xavier-morera Since no new development will be done soon I guess it is maybe better to release the next version from the development branch.

**Comment by xavier-morera** [comment]
Working on it...

**Comment by gjunge** [comment]
@xavier-morera  this can be closed

**Comment by xavier-morera** [comment]
Done. 

Another comment, what do you think if I create a tag called "reopen-if-needed" and close the current outstanding issues? Some are several years old and that way we get a "fresh start" so that we could focus on current outstanding issues.

We could do something similar as well with branches, as we have several that are outdated and the feature was never implemented.

Sometimes pushing the reset button can help bring some order, and I believe we are in such a scenario.

Thoughts?

**Comment by gjunge** [comment]
@xavier-morera Totally agree. 
What shall we do with the open Pull Requests? Most of them, if not all of them won't even compile I guess.

**Comment by xavier-morera** [comment]
Continued here: https://github.com/SolrNet/SolrNet/issues/338
