### ISSUE TITLE
Question - Are you working on a .NET Core 2.0 version? 

### ISSUE THREAD

**Issue by Martin-Andersen** [SolrNet/SolrNet#321]
I have started  porting our search api to core 2, it will save os money because we can use linux instead of windows, half price on AWS.

Are you working on a core version? Or should I fork this project?

I know that the project is now standard 2.0 compliant and that should make it easy to port it to core. Or am I kidding my self (-:

**Comment by xavier-morera** [comment]
Please fork and contribute! It would be deeply appreciated.

Are you going to use SolrCloud? If that is the case, can you give me until tomorrow to merge the cloud branch into develop so that you can benefit from that work

**Comment by gjunge** [comment]
@Martin-Andersen you can just use the netstandard 2.0 library, see this graph:
![image](https://user-images.githubusercontent.com/194466/31858745-2f5ca3b4-b708-11e7-9513-cdc03c92d324.png)

As an analogy one can say that netstandard is like an interface, while net core, xamarin and the full framework, are like classes that implement the interface.

So our netstandard 2.0 library is compatible with netcore 2.0:
![image](https://user-images.githubusercontent.com/194466/31858756-70970f86-b708-11e7-82c2-9a1fe185b913.png)
(see : https://github.com/dotnet/standard/blob/master/docs/versions.md)

**Comment by Martin-Andersen** [comment]
Thanks but I want to run this on a linux, and when I add the packages I get a warning:

`Warning	NU1701	Package 'SolrNet 0.8.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
`

Am I doing something wrong. Have only been working with .NET Core for 3 days (:

And while I am at it, thanks for a great library have been using it since version 0.5 alpha

**Comment by Martin-Andersen** [comment]
@xavier-morera I will fork the project later today and try to convert it to core

**Comment by gjunge** [comment]
@martin-andersen which package are you using?
I assume you are using SolrNet, you should use SolrNet.Microsoft.DependencyInjection, this package has he new Dependency Injection and uses the SolrNet core, both are netstandard. 

SolrNet package  reference the SolrNet.Core package which is netstandard, but also commonservicelocator for DI which is not netstandard (yet, they just released a netstandard version).

**Comment by Martin-Andersen** [comment]
@gjunge thanks a gazillion. Is "SolrNet.Microsoft.DependencyInjection" an official port? Anyway just very happy.
Was forking the SolrNet repo and I am glad I saved many hours porting it.
@xavier-morera will you comment on this? I am still a little confused

**Comment by gjunge** [comment]
SolrNet.Core is the main library, but it kind of needs a DI library to work. So SolrNet comes with many official DI implementations, Ninject, Autofac, Windsor,Structuremap etc. All are part of this Github repo, so official. We just added the MS Dependency Injection support. 
See here the different initialization ways: https://github.com/SolrNet/SolrNet/blob/master/Documentation/Initialization.md

The default Dependency Injection library used to be commonservicelocator, by Microsoft. It used to be part of the main project and thus used to be part of the SolrNet package. We have separated these two, but in order to be backward compatible we left the SolrNet NuGet package combined (so this includes the Core and the commonservicelocator support).

**Comment by nacoleman** [comment]
Loving the SolrNet project but I am seeing the same message as above:

Warning NU1701 Package 'SolrNet 0.8.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

I am using Windsor as I can't use SolrNet.Microsoft.DependencyInjection as it doesn't support Key/Name based injection which I use to switch solr cores.

Is there any way around this so I can be standard 2.0 compliant and use Windsor?

Many Thanks

**Comment by gjunge** [comment]
@nacoleman our Windsor integration still depends on Windsor 3.4, which doesn’t support netstandard yet. 3 months ago Windsor 4.0 and 4.1 came out and they do support netstandard 1.6. 
So what has to be done is upgrade the Windsor integration project so it becomes a netstandard project and takes a Dependency on Windsor 4.1. In addition its Nuspec file has to be updated. 
So in the hope that between 3.4 and 4.1 of Windsor there were no break changes this should be a relatively easy job. 

I see if I get to it next week but feel free to pick it up before.

**Comment by nacoleman** [comment]
thanks gjunge. that's great. I'll wait for the updated nuget package.

**Comment by xavier-morera** [comment]
@gjunge can you take a quick look at the Castle upgrade? There is a reference error in develop branch.

If you have a chance to fix this issue I can publish 0.9.1. Please?

**Comment by gjunge** [comment]
@xavier-morera This one can be closed, and can you create a 0.9.1 release tag?

**Comment by xavier-morera** [comment]
Done on both @gjunge

**Comment by nacoleman** [comment]
thanks for working on this guys.  has something else change though?

I just upgraded and have immediately lost Castle.Facilities.SolrNetIntegration.. cant import that namespace and therefore can't use SolrNetFacility;

Cheers

**Comment by gjunge** [comment]
@nacoleman Will try to have a look tomorrow.

**Comment by gjunge** [comment]
@nacoleman  see #331 
I'll see if I can get a fix out soon.

**Comment by xavier-morera** [comment]
@gjunge has provided a fix. Thanks again

**Comment by adegroff** [comment]
@Martin-Andersen: Have you been able to successfully port this library over to .NET Core?
@xavier-morera: If so, has this been merged into this repo?

**Comment by Martin-Andersen** [comment]
@xavier-morera I got it to work with this package https://github.com/SolrNet/SolrNet/blob/master/Documentation/Initialization.md

**Comment by nacoleman** [comment]
I have this working in .net core environment. Thanks guys

**Comment by xavier-morera** [comment]
Thanks to you
