### ISSUE TITLE
How to use basic authentication in asp.net core

### ISSUE THREAD

**Issue by bidianqing** [SolrNet/SolrNet#350]
How to use basic authentication in asp.net core

**Comment by bidianqing** [comment]
and also Multi-core what to do in asp.net core?

**Comment by gjunge** [comment]
The Microsoft Dependency injection is rather simple, and so far doesn't support multi core. 
Most of the other DI's do support multi core, and in our next release (currently in develop branch), many more of them will be netstandard 2.0 compliant, meaning you can use them in your ASP.NET core project.

Also using basic authentication with Microsoft Dependency Injection will be harder, because you will have to swap out the regular `HttpWebRequestFactory` with the `BasicAuthHttpWebRequestFactory`. Other DI do support those scenarios.
