### ISSUE TITLE
Update SolrNet.StructureMap to .Net Standard 2.0

### ISSUE THREAD

**Issue by CiprianMo** [SolrNet/SolrNet#372]
Hi, I would like to contribute to the library by updating SolrNet.StructureMap to .Net Standard 2.0 , as I'm using StructureMap di container extensively.

**Comment by gjunge** [comment]
@ciprianmo that would be wonderful! 
Our goal is indeed to have all our DI integrations up to date. 

Just an FYI, the “pitfall” with the StructureMap integration is that it uses configuration from the old System.Configuration namespace. 

I do not know whether that is still a functionality which is still in use. If it is than we just have to exclude those files dealing with System.Configuration from the netstandard 2.0 version (conditional ItemGroup).

**Comment by CiprianMo** [comment]
@gjunge just as an experiment I updated SolrNet.StructureMap to .Net Standard 2.0, and for System.Configuration I had to install a different nuget System.Configuration.ConfigurationManager. This made the project build and most of the tests pass, except two. I don't know yet if those tests that didn't pss have to do with System.Configuration or not.
Tomorrow I will be looking into where and how this System.Configuration is used and whether I can exclude it.

**Comment by gjunge** [comment]
@ciprianmo it could be that those test are integration tests (see the trait attribute), that need a Solr instance running (and even then might fail since the integration tests are rather outdated). So if this is the case you may ignore hem. 
Besides that great news that all seems to compile from the start. 

And could you in the end update the readme.md and  Initialization.md fieles with the relevant changes?

Thanks again for contributing!!!
