### ISSUE TITLE
JSON Facet API

### ISSUE THREAD

**Issue by sumit4bansal** [SolrNet/SolrNet#456]
Any plan to include Json Facet api? https://github.com/SolrNet/SolrNet/issues/418

**Comment by xmorera** [comment]
No work done yet @sumit4bansal. But if you contribute to this functionality, it could be released as part of SolrNet.

**Comment by sumit4bansal** [comment]
Thanks @xmorera, I passed the Json.Facet parametrs through ExtraParams, and read the response by updating FacetsResponseParser.ParseFacetFields function, added Json.Facet response in facet dictionary with key "JsonFacets", This code change is working.

` public IDictionary<string, ICollection<KeyValuePair<string, int>>> ParseFacetFields(XElement node, XElement mainJsonFacetNode)
        {
             
            if (mainJsonFacetNode != null)
            {
                var c = new List<KeyValuePair<string, int>>();
                foreach (var facetNode in mainJsonFacetNode.Elements())
                {
                    var nameAttr = facetNode.Attribute("name");
                    var key = nameAttr == null ? "" : nameAttr.Value;
                    var value = Convert.ToInt32(facetNode.Value);
                    c.Add(new KeyValuePair<string, int>(key, value));
                }
                d["JsonFacets"] = c;
            }

            return d;
        }`

**Comment by stephen-zhao** [comment]
I'm interested in adding JSON facet support to the library. Could we re-open this issue? @xmorera

**Comment by xmorera** [comment]
Hello Stephen. I defer to @mausch which is the one that calls the shots over here!

**Comment by stephen-zhao** [comment]
I can come up with a quick writeup when I get a chance. I haven't delved into the code for this lib yet, but I'm thinking it would involve basically specifying a data model for the request side and a data model for the response side, both being as specific as possible with field names and types. I recall newer (possibly still in development) Solr versions seem to have proper OAPI spec which would allow us to generate the whole request/response data model automatically. But until then might need something manual. Due to the dynamic nature of some of the request/response objects, it would be nice to make extensive use of C# generics to allow consumer of the lib to fully customize the data model to their needs (e.g. what facets to run, what fields to return, etc).

**Comment by ptik31** [comment]
Hi

Since we need the JSON facet API in our project, which is based on this SolrNet repository, we have created our own temporary implementation until the feature is officially implemented.
So, feel free to take inspiration from here.

We hope to be able to switch back to an official version soon.

[JSON Facet API](https://github.com/ptik31/SolrNet/commit/b2950a65f5c77b542ad161c0138689e4dfc0a449)
