### ISSUE TITLE
"Added convert to UTC" , this issue is a not good idea .  

### ISSUE THREAD

**Issue by Vettel-H-Xue** [SolrNet/SolrNet#527]
This issue is a not good idea .  

And caused an accident in my organization.

This idea is like adding a layer of Russian dolls to Solr.

Convert to UTC when saving and local time when reading.

Why have this idea?

**Comment by mausch** [comment]
Hi @JokXue , can you expand a bit more on the issue you're having?

By "Added convert to UTC" I imagine you're talking about the change made in this commit? https://github.com/SolrNet/SolrNet/commit/c80005fe78f687821b29e200cc6a518aeecfcac6

Can you explain what issues this has caused you? Preferably with some code of course :slightly_smiling_face:

**Comment by JokXue** [comment]
Hi @mausch , 
I think the SolrNet was a Middleware.  The data passed to Solr through SolrNET should be saved in Solr as it is. But it does not. 
The "Added convert to UTC" change changes the time of the incoming PST time zone to UTC time. 
And the reading program has not changed this. The causes data errors in the production environment. 
So I had to clone the entire Solrnet code, modify the code and compile it for use. 
These are my modified : 
![image](https://user-images.githubusercontent.com/26120880/100035740-d36bc100-2e39-11eb-8fdb-d2c27d7ec6e3.png)


> Hi @JokXue , can you expand a bit more on the issue you're having?
> 
> By "Added convert to UTC" I imagine you're talking about the change made in this commit? [c80005f](https://github.com/SolrNet/SolrNet/commit/c80005fe78f687821b29e200cc6a518aeecfcac6)
> 
> Can you explain what issues this has caused you? Preferably with some code of course 🙂

**Comment by mausch** [comment]
I see what you mean. However, the thing is, [Solr stores dates in UTC](https://lucene.apache.org/solr/6_2_0/solr-core/org/apache/solr/schema/TrieDateField.html), so SolrNet here is just making sure that the dates are properly in UTC. 
Otherwise other clients in different timezones or in different platforms (e.g. a Java client) would get the wrong date.
For DateTimeOffset fields this shouldn't be generally an issue because, well, the timezone is right there embedded in the type :slightly_smiling_face: 
For DateTime fields, things suck a bit because the type is somewhat ambiguous about the concrete timezone (that's why [Microsoft has been recommending using DateTimeOffset ever since introducing it](https://docs.microsoft.com/en-us/dotnet/standard/datetime/choosing-between-datetime)) so again SolrNet just makes sure that the dates are in UTC when storing them, and [SolrNet will also set the DateTimeKind to UTC when fetching from Solr](https://github.com/SolrNet/SolrNet/blob/5983baa5c2b7385fe4468d655cf456ba003a2fb6/SolrNet/Impl/FieldParsers/DateTimeFieldParser.cs#L53).

Does that make sense?

FWIW I do think this should be documented more explicitly.

**Comment by fllo** [comment]
The DateTime issue is larger: https://blog.nodatime.org/2011/08/what-wrong-with-datetime-anyway.html

The solution would probably be to support and use NodaTime.

**Comment by mausch** [comment]
Discussing NodaTime vs DateTime vs DateTimeOffset is really out of the scope of SolrNet.

Having said that, if you have special requirements that aren't served by DateTimeOffset e.g. representing a moment in time in a _specific_ timezone as mentioned in that article, SolrNet's serializers are fully pluggable: you can register serializers for your own types or even replace the default serializers if you want to (just implement ISolrFieldSerializer / ISolrFieldParser), so any application can "support NodaTime" with a few lines of code without changing anything in the SolrNet codebase.
