### ISSUE TITLE
Very large numFound values cause OverflowException

### ISSUE THREAD

**Issue by zuccaro** [SolrNet/SolrNet#555]
When querying to obtain document count (`*:*`, rows=`0`) or issuing broad queries on a large collection (>2,147,483,647 documents), `SolrNet.Impl.ResponseParsers.ResultsResponseParser<T>` throws a `System.OverflowException` when attempting to set the `numFound` property.  Propose changing `numFound` from `int` to `long` in `SolrNet.Impl. AbstractSolrQueryResults<T>`, `SolrNet.Impl.ResponseParsers.ResultsResponseParser<T>`, etc.  

Willing to submit this as a PR. 🙇

**Comment by mausch** [comment]
Fixed now! I'm a bit tired so I read StackOverflowException instead of OverflowException and spent some 5 minutes looking for the recursion in that code :smile:

**Comment by Phoosha** [comment]
Hi, just wondering: Wouldn't this also affect other places like `AbstractSolrQueryResults.FacetFields` since a facet count is essentially also a document count just like `NumFound`?

If so, I guess there's a bunch of properties in `AbstractSolrQueryResults` that also need changes: `FacetFields`, `FacetDates`, `FacetRanges`, `FacetIntervals`, `FacetPivots` and possibly others I haven't thought of. Just a random thought I got, when fixing a cast error in a test that compared `NumFound` to a Facet count.

Thanks for taking care of this project.
