### ISSUE TITLE
SolrFacetFieldQuery MinCount =1 not being honored

### ISSUE THREAD

**Issue by usoblaze** [SolrNet/SolrNet#626]
Aloha,

Please bear with me as this is my first time reporting an issue on GitHub!

I'm having some trouble with the MinCount parameter of a SolrFacetFieldQuery when the value is set to 1. Based on the documentation, my understanding is that MinCount maps to Solr's facet.minCount parameter, which should denote to Solr that if the facet field's count is less than that value, the facet field should not be returned in the response. In my case, I'm setting them all to 1 so my expectation is that anything less than 1 is not returned.  

Let's start with some basics of my application:

Version of SolrNet: 1.1.1
Target framework: .NET Framework 4.7.2

Something else that's noteworthy is that I'm faceting on dynamic string fields. Typically this isn't possible because Solr doesn't support faceting on wildcards, however, I'm capturing all of the dynamic field names during an import in an entirely different application, then feeding them into my facet fields. Also, I'm using a PostSolrConnection to workaround the Uri length limitation. Here's what I'm seeing:

![2024-10-11_16-22-14](https://github.com/user-attachments/assets/09fd8125-b383-4733-9ff4-6e1dd5d91bf7)

In the screenshot above, I've expanded the "queryOptions" variable that I'm passing into solr.Query and drilled down into Facet then Queries structures. You'll notice that one of my queries is on a Field named "attr_EN_Battery_Type" with a Limit=1000 and MinCount=1. This is what the results look like:

![2024-10-11_16-24-52](https://github.com/user-attachments/assets/4f2a5ce3-a309-4dd4-93d6-e3c3288e1b0a)

You'll notice this happening for all of my facets. I'm faceting on 796 fields and I'm seeing 796 items in the response's FacetFields. For some greater context, here's a snippet of the code which should illustrate the approach for faceting. I'm explicitly setting these values.

![2024-10-11_16-27-37](https://github.com/user-attachments/assets/2b39b3b9-6cf6-4138-9a03-ae48ac9f65cb)

I tried setting MinCount=1 on the FacetParameters in the query but to no avail. I also tried setting the Exists parameter to true to cap facet counts at 1 but I get the same behavior and see facet fields with counts > 1.  I even tried setting MinCount=2 and stripping off the Exists parameter and still get the same behavior. 

Is there some other way to go about this? I understand that I can filter these empty values out before the data is handed to my View but for the sake of efficiency and performance, I'm hoping to not have those empty structures returned in the query response.

**Comment by mausch** [comment]
Aloha! A few ideas to diagnose this:

- Install LoggingConnection in your code ( for reference see https://github.com/SolrNet/SolrNetSampleApps/blob/d9142d66121fa4058cfa67a650ca11f2fbb56b9e/SampleSolrApp/Startup.cs#L33 ). Then copy the Solr query generated by SolrNet into the Solr UI and see if the issue is there. Maybe the necessary query bits are not being generated for some reason, maybe the actual behaviour from Solr is not what is expected for some reason, etc.
- [Facet mincount is used in the sample app](https://github.com/SolrNet/SolrNetSampleApps/blob/d9142d66121fa4058cfa67a650ca11f2fbb56b9e/SampleSolrApp/Controllers/HomeController.cs#L42). See if you can tweak that code to reproduce your issue.

> Please bear with me as this is my first time reporting an issue on GitHub!

You did fine! :slightly_smiling_face: 

The ideal github issue is a stand-alone, minimal repro of the problem. The closer you get to that ideal the easier it will be for the maintainer to address your problem (and fix the underlying bug if that were the case).
Prioritise working code / tests over screenshots.
Otherwise there will be guesswork. Most open source maintainers in smallish projects have little incentive to engage in that.

**Comment by usoblaze** [comment]
Thanks for the advice!

I took a slightly different approach and rather than logging on the app's end, I enabled slow query logging on Solr's end with a value of 0. All of the query parameters are making it to the server so it's not a SolrNet problem.

In fact, I believe SolrNet is working as expected and I completely misunderstood the intent of the field. Originally, I thought that setting MinCount = 1 meant that the whole node would be omitted from the FacetFields structure in the query response if there are no applicable facet values. After experimenting in Solr directly, I noticed it **always** returns the facet field. If there are no applicable facets, the structure is empty which is ultimately what I see in the query response: existence of the facet but an empty collection.

Again, many thanks for your help! Big fan of your work!
