### ISSUE TITLE
Async operations

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#91]
(moved from https://code.google.com/p/solrnet/issues/detail?id=120 )

Implement APM (begin/end pattern) for async operations.

APM is supported in .NET 3.5 and [Task can easily wrap APM](http://msdn.microsoft.com/en-us/library/dd997423.aspx).

**Comment by erandr** [comment]
Has Async support added yet?

**Comment by mausch** [comment]
@erandr This issue is still open, feel free to contribute to the solution.

**Comment by gjunge** [comment]
With .NET 4.6 just around the corner, and the TPL library being here to stay, it might be a good time for Solrnet to giving first class support to the current version of .NET instead of trying to support version 3.5.

At the moment, as I see it, the community wants to push this project forward, trying to add features the community desires, while you just pick the pull-request that don't harm your own projects.
Which is your right to do so, but it is a bummer for many potential contributers.

My proposed solution is to branch Solrnet into a legacy branch, which supports .NET 3.5, but have the main branch run ahead full steam.

Your thoughts?

**Comment by stanuku** [comment]
I agree with gjunge's latest comment. 

@mausch could you please reply? thanks

**Comment by kowy** [comment]
I also agree with gjunge opinion. SolrNet is a great project, but we should move forward and and async/await is really useful feature.

**Comment by xavier-morera** [comment]
My suggestion would be to first take a look and see what are the priorities. So far I am inclined to think they would be:
- SolrCloud
- Support for newer versions of Solr, including breaking changes
- Async support
- Multiple .NET versions
- NuGet

These are the ones that come to mind. I will put together a quick poll to get feedback and understand what are the priorities according to the users and then we can start working

**Comment by gjunge** [comment]
I agree with you regarding the priorities, yet we have multiple contributors wanting to contribute. So we might be able to work on various items at the same time. 

For Async support to be developed , a decision needs to be made on how to do it (support multiple .NET versions, for example like Newtonsoft.Json, or just 4.5 and up). 
Hopefully enough people will answer the questionairre, so we can get a view on what .NET versions are in use by the SolrNet users.

**Comment by xavier-morera** [comment]
Agreed. Will give it a few days to get more feedback.

**Comment by gjunge** [comment]
Some work in progress over here: [async-support branch](https://github.com/gjunge/SolrNet/tree/async-support)

**Comment by xavier-morera** [comment]
Closed
